#!/bin/sh
# preinst script for libqrack
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#        * <old-preinst> `abort-upgrade' <new-version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    install|upgrade)
        cp -r cmake ../cmake
        cp CMakeLists.txt ../CMakeLists.txt
        cp libqrack.pc.in ../libqrack.pc.in
        cp -r include ../include
        cp -r src ../src
        cp -r tests ../tests
        cp -r debian ../debian
        cp LICENSE.md ../LICENSE.md
        cp README.md ../README.md

        rm -r *

        cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib -DPACK_DEBIAN=ON -DCPP_STD=14 -DENABLE_RDRAND=OFF -DENABLE_DEVRAND=ON -DENABLE_OPENCL=ON -DQBCAPPOW=12 -DFPPOW=5 ..
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
